export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID_PENDING_SHIPMENT = 'PAID_PENDING_SHIPMENT',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
}
